{-# language CPP #-}
module Vulkan.Extensions.VK_EXT_shader_demote_to_helper_invocation  (PhysicalDeviceShaderDemoteToHelperInvocationFeaturesEXT) where

import Data.Kind (Type)
import Vulkan.CStruct (FromCStruct)
import Vulkan.CStruct (ToCStruct)
data PhysicalDeviceShaderDemoteToHelperInvocationFeaturesEXT

instance ToCStruct PhysicalDeviceShaderDemoteToHelperInvocationFeaturesEXT
instance Show PhysicalDeviceShaderDemoteToHelperInvocationFeaturesEXT

instance FromCStruct PhysicalDeviceShaderDemoteToHelperInvocationFeaturesEXT

