{-# language CPP #-}
module Vulkan.Extensions.VK_NVX_multiview_per_view_attributes  (PhysicalDeviceMultiviewPerViewAttributesPropertiesNVX) where

import Data.Kind (Type)
import Vulkan.CStruct (FromCStruct)
import Vulkan.CStruct (ToCStruct)
data PhysicalDeviceMultiviewPerViewAttributesPropertiesNVX

instance ToCStruct PhysicalDeviceMultiviewPerViewAttributesPropertiesNVX
instance Show PhysicalDeviceMultiviewPerViewAttributesPropertiesNVX

instance FromCStruct PhysicalDeviceMultiviewPerViewAttributesPropertiesNVX

