{-# language CPP #-}
module Vulkan.Extensions.VK_NV_dedicated_allocation_image_aliasing  (PhysicalDeviceDedicatedAllocationImageAliasingFeaturesNV) where

import Data.Kind (Type)
import Vulkan.CStruct (FromCStruct)
import Vulkan.CStruct (ToCStruct)
data PhysicalDeviceDedicatedAllocationImageAliasingFeaturesNV

instance ToCStruct PhysicalDeviceDedicatedAllocationImageAliasingFeaturesNV
instance Show PhysicalDeviceDedicatedAllocationImageAliasingFeaturesNV

instance FromCStruct PhysicalDeviceDedicatedAllocationImageAliasingFeaturesNV

