resolver: lts-18.13
packages:
- .
- utils
- examples
- VulkanMemoryAllocator
- openxr
extra-deps:
- autoapply-0.4.1.1
- th-desugar-1.12
- derive-storable-0.3.0.0
- derive-storable-plugin-0.2.3.4
- nothunks-0.1.4

nix:
  enable: false
  packages: [vulkan-loader vulkan-headers glslang pkg-config SDL2 zlib]
