resolver: lts-22.44
packages:
- .
- utils
- utils-spirv
- utils-init/vulkan-init-sdl2
- utils-init/vulkan-init-glfw
- examples
- VulkanMemoryAllocator
- openxr
- generate-new

extra-deps:
- unification-fd-0.12.0.2
# generate-new
- validation-selective-0.2.0.0
- geomancy-0.3.0.1
- gl-block-1.1
- ptrdiff-0
- spirv-enum-1.104.350.0
- spirv-reflect-ffi-0.4
- spirv-reflect-types-0.4
- webcolor-labels-0.1.0.0

# use ghcup, nix, setup actions
system-ghc: true
install-ghc: false

allow-newer: true

nix:
  enable: false
  packages: [vulkan-loader vulkan-headers glslang pkg-config SDL2 zlib]
