resolver: lts-22.44
packages:
- .
- utils
- examples
- VulkanMemoryAllocator
- openxr
extra-deps:
- unification-fd-0.12.0.2
- derive-storable-0.3.1.0
- derive-storable-plugin-0.2.3.7

# use ghcup, nix, setup actions
system-ghc: true
install-ghc: false

allow-newer: true

nix:
  enable: false
  packages: [vulkan-loader vulkan-headers glslang pkg-config SDL2 zlib]
