name: vulkan-utils
version: "0.4.1"
synopsis: Utils for the vulkan package
category: Graphics
maintainer: Joe Hermaszewski <live.long.and.prosper@monoid.al>
github: expipiplus1/vulkan
extra-source-files:
  - readme.md
  - changelog.md
  - package.yaml
  - src/Vulkan/Utils/gl_enums.h

library:
  source-dirs: src
  c-sources: cbits/DebugCallback.c
  other-modules:
    - Vulkan.Utils.Internal
  dependencies:
    - base <5
    - bytestring
    - containers
    - dependent-map
    - dependent-sum
    - extra
    - file-embed
    - filepath
    - resourcet >= 1.2.4
    - template-haskell
    - temporary
    - text
    - transformers
    - typed-process
    - unordered-containers
    - vector
    - vulkan >= 3.6.14 && < 3.10

tests:
  doctests:
    main: Doctests.hs
    other-modules: ""
    source-dirs:
      - test/doctest
    dependencies:
      - base
      - doctest
      - vulkan-utils

custom-setup:
  dependencies:
    - base
    - Cabal
    - cabal-doctest >= 1 && <1.1

ghc-options:
  - -Wall

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - DerivingStrategies
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MagicHash
  - NamedFieldPuns
  - NoMonomorphismRestriction
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternSynonyms
  - PolyKinds
  - QuantifiedConstraints
  - RankNTypes
  - RecordWildCards
  - RoleAnnotations
  - ScopedTypeVariables
  - StandaloneDeriving
  - Strict
  - TupleSections
  - TypeApplications
  - TypeFamilyDependencies
  - TypeOperators
  - TypeSynonymInstances
  - ViewPatterns
