name: vulkan-init-glfw
version: "0.1.0.0"
synopsis: Vulkan initialization helpers for GLFW
category: Graphics
maintainer: Ellie Hermaszewska <live.long.and.prosper@monoid.al>
github: expipiplus1/vulkan
license: BSD3
license-file: LICENSE
extra-source-files:
- readme.md
- changelog.md
- package.yaml

library:
  source-dirs: src
  dependencies:
  - base <5
  - bytestring
  - GLFW-b >= 3.3 && < 3.4
  - resourcet >= 1.2.4
  - vector
  - vulkan >= 3.6.14 && < 3.28
  - vulkan-utils

ghc-options:
- -Wall

default-extensions:
- DerivingStrategies
- FlexibleContexts
- LambdaCase
- NamedFieldPuns
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
