{-# language Strict #-}
{-# language CPP #-}
{-# language PatternSynonyms #-}

module Graphics.Vulkan.Extensions.VK_IMG_format_pvrtc
  ( pattern VK_IMG_FORMAT_PVRTC_SPEC_VERSION
  , pattern VK_IMG_FORMAT_PVRTC_EXTENSION_NAME
  , pattern VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG
  , pattern VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG
  , pattern VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG
  , pattern VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG
  , pattern VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG
  , pattern VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG
  , pattern VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG
  , pattern VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG
  ) where




import Graphics.Vulkan.C.Extensions.VK_IMG_format_pvrtc
  ( pattern VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG
  , pattern VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG
  , pattern VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG
  , pattern VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG
  , pattern VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG
  , pattern VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG
  , pattern VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG
  , pattern VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG
  , pattern VK_IMG_FORMAT_PVRTC_EXTENSION_NAME
  , pattern VK_IMG_FORMAT_PVRTC_SPEC_VERSION
  )

