{-# language Strict #-}
{-# language CPP #-}
{-# language PatternSynonyms #-}

module Graphics.Vulkan.Extensions.VK_KHR_sampler_ycbcr_conversion
  ( BindImagePlaneMemoryInfoKHR
  , ImagePlaneMemoryRequirementsInfoKHR
  , PhysicalDeviceSamplerYcbcrConversionFeaturesKHR
  , SamplerYcbcrConversionCreateInfoKHR
  , SamplerYcbcrConversionImageFormatPropertiesKHR
  , SamplerYcbcrConversionInfoKHR
  , SamplerYcbcrConversionKHR
  , createSamplerYcbcrConversionKHR
  , destroySamplerYcbcrConversionKHR
  , pattern CHROMA_LOCATION_COSITED_EVEN_KHR
  , pattern CHROMA_LOCATION_MIDPOINT_KHR
  , pattern DEBUG_REPORT_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_KHR_EXT
  , pattern FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16_KHR
  , pattern FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16_KHR
  , pattern FORMAT_B16G16R16G16_422_UNORM_KHR
  , pattern FORMAT_B8G8R8G8_422_UNORM_KHR
  , pattern FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT_KHR
  , pattern FORMAT_FEATURE_DISJOINT_BIT_KHR
  , pattern FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT_KHR
  , pattern FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT_KHR
  , pattern FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT_KHR
  , pattern FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT_KHR
  , pattern FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT_KHR
  , pattern FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16_KHR
  , pattern FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16_KHR
  , pattern FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16_KHR
  , pattern FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16_KHR
  , pattern FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16_KHR
  , pattern FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16_KHR
  , pattern FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16_KHR
  , pattern FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16_KHR
  , pattern FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16_KHR
  , pattern FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16_KHR
  , pattern FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16_KHR
  , pattern FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16_KHR
  , pattern FORMAT_G16B16G16R16_422_UNORM_KHR
  , pattern FORMAT_G16_B16R16_2PLANE_420_UNORM_KHR
  , pattern FORMAT_G16_B16R16_2PLANE_422_UNORM_KHR
  , pattern FORMAT_G16_B16_R16_3PLANE_420_UNORM_KHR
  , pattern FORMAT_G16_B16_R16_3PLANE_422_UNORM_KHR
  , pattern FORMAT_G16_B16_R16_3PLANE_444_UNORM_KHR
  , pattern FORMAT_G8B8G8R8_422_UNORM_KHR
  , pattern FORMAT_G8_B8R8_2PLANE_420_UNORM_KHR
  , pattern FORMAT_G8_B8R8_2PLANE_422_UNORM_KHR
  , pattern FORMAT_G8_B8_R8_3PLANE_420_UNORM_KHR
  , pattern FORMAT_G8_B8_R8_3PLANE_422_UNORM_KHR
  , pattern FORMAT_G8_B8_R8_3PLANE_444_UNORM_KHR
  , pattern FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16_KHR
  , pattern FORMAT_R10X6G10X6_UNORM_2PACK16_KHR
  , pattern FORMAT_R10X6_UNORM_PACK16_KHR
  , pattern FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16_KHR
  , pattern FORMAT_R12X4G12X4_UNORM_2PACK16_KHR
  , pattern FORMAT_R12X4_UNORM_PACK16_KHR
  , pattern IMAGE_ASPECT_PLANE_0_BIT_KHR
  , pattern IMAGE_ASPECT_PLANE_1_BIT_KHR
  , pattern IMAGE_ASPECT_PLANE_2_BIT_KHR
  , pattern IMAGE_CREATE_DISJOINT_BIT_KHR
  , pattern KHR_SAMPLER_YCBCR_CONVERSION_EXTENSION_NAME
  , pattern KHR_SAMPLER_YCBCR_CONVERSION_SPEC_VERSION
  , pattern OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_KHR
  , pattern SAMPLER_YCBCR_MODEL_CONVERSION_RGB_IDENTITY_KHR
  , pattern SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_2020_KHR
  , pattern SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_601_KHR
  , pattern SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_709_KHR
  , pattern SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_IDENTITY_KHR
  , pattern SAMPLER_YCBCR_RANGE_ITU_FULL_KHR
  , pattern SAMPLER_YCBCR_RANGE_ITU_NARROW_KHR
  , pattern STRUCTURE_TYPE_BIND_IMAGE_PLANE_MEMORY_INFO_KHR
  , pattern STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO_KHR
  , pattern STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES_KHR
  , pattern STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO_KHR
  , pattern STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES_KHR
  , pattern STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_INFO_KHR
  , SamplerYcbcrModelConversionKHR
  , SamplerYcbcrRangeKHR
  , ChromaLocationKHR
  , pattern STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO
  , pattern STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_INFO
  , pattern STRUCTURE_TYPE_BIND_IMAGE_PLANE_MEMORY_INFO
  , pattern STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO
  , pattern STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES
  , pattern STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES
  , pattern DEBUG_REPORT_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_EXT
  , pattern OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION
  , pattern FORMAT_G8B8G8R8_422_UNORM
  , pattern FORMAT_B8G8R8G8_422_UNORM
  , pattern FORMAT_G8_B8_R8_3PLANE_420_UNORM
  , pattern FORMAT_G8_B8R8_2PLANE_420_UNORM
  , pattern FORMAT_G8_B8_R8_3PLANE_422_UNORM
  , pattern FORMAT_G8_B8R8_2PLANE_422_UNORM
  , pattern FORMAT_G8_B8_R8_3PLANE_444_UNORM
  , pattern FORMAT_R10X6_UNORM_PACK16
  , pattern FORMAT_R10X6G10X6_UNORM_2PACK16
  , pattern FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16
  , pattern FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16
  , pattern FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16
  , pattern FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16
  , pattern FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16
  , pattern FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16
  , pattern FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16
  , pattern FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16
  , pattern FORMAT_R12X4_UNORM_PACK16
  , pattern FORMAT_R12X4G12X4_UNORM_2PACK16
  , pattern FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16
  , pattern FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16
  , pattern FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16
  , pattern FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16
  , pattern FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16
  , pattern FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16
  , pattern FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16
  , pattern FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16
  , pattern FORMAT_G16B16G16R16_422_UNORM
  , pattern FORMAT_B16G16R16G16_422_UNORM
  , pattern FORMAT_G16_B16_R16_3PLANE_420_UNORM
  , pattern FORMAT_G16_B16R16_2PLANE_420_UNORM
  , pattern FORMAT_G16_B16_R16_3PLANE_422_UNORM
  , pattern FORMAT_G16_B16R16_2PLANE_422_UNORM
  , pattern FORMAT_G16_B16_R16_3PLANE_444_UNORM
  , pattern IMAGE_ASPECT_PLANE_0_BIT
  , pattern IMAGE_ASPECT_PLANE_1_BIT
  , pattern IMAGE_ASPECT_PLANE_2_BIT
  , pattern IMAGE_CREATE_DISJOINT_BIT
  , pattern FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT
  , pattern FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT
  , pattern FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT
  , pattern FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT
  , pattern FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT
  , pattern FORMAT_FEATURE_DISJOINT_BIT
  , pattern FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT
  , pattern SAMPLER_YCBCR_MODEL_CONVERSION_RGB_IDENTITY
  , pattern SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_IDENTITY
  , pattern SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_709
  , pattern SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_601
  , pattern SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_2020
  , pattern SAMPLER_YCBCR_RANGE_ITU_FULL
  , pattern SAMPLER_YCBCR_RANGE_ITU_NARROW
  , pattern CHROMA_LOCATION_COSITED_EVEN
  , pattern CHROMA_LOCATION_MIDPOINT
  ) where

import Data.String
  ( IsString
  )


import Graphics.Vulkan.C.Core10.Core
  ( VkFormat(..)
  , VkObjectType(..)
  , VkStructureType(..)
  )
import Graphics.Vulkan.C.Core10.DeviceInitialization
  ( VkFormatFeatureFlagBits(..)
  , VkImageCreateFlagBits(..)
  )
import Graphics.Vulkan.C.Core10.SparseResourceMemoryManagement
  ( VkImageAspectFlagBits(..)
  )
import Graphics.Vulkan.C.Core11.Promoted_from_VK_KHR_sampler_ycbcr_conversion
  ( VkChromaLocation(..)
  , VkSamplerYcbcrModelConversion(..)
  , VkSamplerYcbcrRange(..)
  )
import Graphics.Vulkan.C.Extensions.VK_EXT_debug_report
  ( VkDebugReportObjectTypeEXT(..)
  )
import Graphics.Vulkan.C.Extensions.VK_KHR_sampler_ycbcr_conversion
  ( pattern VK_KHR_SAMPLER_YCBCR_CONVERSION_EXTENSION_NAME
  , pattern VK_KHR_SAMPLER_YCBCR_CONVERSION_SPEC_VERSION
  )
import Graphics.Vulkan.Core10.Core
  ( pattern FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16
  , pattern FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16
  , pattern FORMAT_B16G16R16G16_422_UNORM
  , pattern FORMAT_B8G8R8G8_422_UNORM
  , pattern FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16
  , pattern FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16
  , pattern FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16
  , pattern FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16
  , pattern FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16
  , pattern FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16
  , pattern FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16
  , pattern FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16
  , pattern FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16
  , pattern FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16
  , pattern FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16
  , pattern FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16
  , pattern FORMAT_G16B16G16R16_422_UNORM
  , pattern FORMAT_G16_B16R16_2PLANE_420_UNORM
  , pattern FORMAT_G16_B16R16_2PLANE_422_UNORM
  , pattern FORMAT_G16_B16_R16_3PLANE_420_UNORM
  , pattern FORMAT_G16_B16_R16_3PLANE_422_UNORM
  , pattern FORMAT_G16_B16_R16_3PLANE_444_UNORM
  , pattern FORMAT_G8B8G8R8_422_UNORM
  , pattern FORMAT_G8_B8R8_2PLANE_420_UNORM
  , pattern FORMAT_G8_B8R8_2PLANE_422_UNORM
  , pattern FORMAT_G8_B8_R8_3PLANE_420_UNORM
  , pattern FORMAT_G8_B8_R8_3PLANE_422_UNORM
  , pattern FORMAT_G8_B8_R8_3PLANE_444_UNORM
  , pattern FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16
  , pattern FORMAT_R10X6G10X6_UNORM_2PACK16
  , pattern FORMAT_R10X6_UNORM_PACK16
  , pattern FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16
  , pattern FORMAT_R12X4G12X4_UNORM_2PACK16
  , pattern FORMAT_R12X4_UNORM_PACK16
  , pattern OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION
  , pattern STRUCTURE_TYPE_BIND_IMAGE_PLANE_MEMORY_INFO
  , pattern STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO
  , pattern STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES
  , pattern STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO
  , pattern STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES
  , pattern STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_INFO
  )
import Graphics.Vulkan.Core10.DeviceInitialization
  ( AllocationCallbacks(..)
  , Device(..)
  , pattern FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT
  , pattern FORMAT_FEATURE_DISJOINT_BIT
  , pattern FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT
  , pattern FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT
  , pattern FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT
  , pattern FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT
  , pattern FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT
  , pattern IMAGE_CREATE_DISJOINT_BIT
  )
import Graphics.Vulkan.Core10.SparseResourceMemoryManagement
  ( pattern IMAGE_ASPECT_PLANE_0_BIT
  , pattern IMAGE_ASPECT_PLANE_1_BIT
  , pattern IMAGE_ASPECT_PLANE_2_BIT
  )
import Graphics.Vulkan.Core11.Promoted_from_VK_KHR_sampler_ycbcr_conversion
  ( BindImagePlaneMemoryInfo(..)
  , ImagePlaneMemoryRequirementsInfo(..)
  , PhysicalDeviceSamplerYcbcrConversionFeatures(..)
  , SamplerYcbcrConversionCreateInfo(..)
  , SamplerYcbcrConversionImageFormatProperties(..)
  , SamplerYcbcrConversionInfo(..)
  , SamplerYcbcrConversion
  , createSamplerYcbcrConversion
  , destroySamplerYcbcrConversion
  , pattern CHROMA_LOCATION_COSITED_EVEN
  , pattern CHROMA_LOCATION_MIDPOINT
  , pattern SAMPLER_YCBCR_MODEL_CONVERSION_RGB_IDENTITY
  , pattern SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_2020
  , pattern SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_601
  , pattern SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_709
  , pattern SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_IDENTITY
  , pattern SAMPLER_YCBCR_RANGE_ITU_FULL
  , pattern SAMPLER_YCBCR_RANGE_ITU_NARROW
  )
import Graphics.Vulkan.Extensions.VK_EXT_debug_report
  ( pattern DEBUG_REPORT_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_EXT
  )
import Graphics.Vulkan.Core11.Promoted_from_VK_KHR_sampler_ycbcr_conversion
  ( ChromaLocationKHR
  , SamplerYcbcrModelConversionKHR
  , SamplerYcbcrRangeKHR
  )


type BindImagePlaneMemoryInfoKHR = BindImagePlaneMemoryInfo
-- TODO: Pattern constructor alias)

type ImagePlaneMemoryRequirementsInfoKHR = ImagePlaneMemoryRequirementsInfo
-- TODO: Pattern constructor alias)

type PhysicalDeviceSamplerYcbcrConversionFeaturesKHR = PhysicalDeviceSamplerYcbcrConversionFeatures
-- TODO: Pattern constructor alias)

type SamplerYcbcrConversionCreateInfoKHR = SamplerYcbcrConversionCreateInfo
-- TODO: Pattern constructor alias)

type SamplerYcbcrConversionImageFormatPropertiesKHR = SamplerYcbcrConversionImageFormatProperties
-- TODO: Pattern constructor alias)

type SamplerYcbcrConversionInfoKHR = SamplerYcbcrConversionInfo
-- TODO: Pattern constructor alias)

-- No documentation found for TopLevel "SamplerYcbcrConversionKHR"
type SamplerYcbcrConversionKHR = SamplerYcbcrConversion

createSamplerYcbcrConversionKHR :: Device ->  SamplerYcbcrConversionCreateInfo ->  Maybe AllocationCallbacks ->  IO (SamplerYcbcrConversion)
createSamplerYcbcrConversionKHR = createSamplerYcbcrConversion

destroySamplerYcbcrConversionKHR :: Device ->  SamplerYcbcrConversion ->  Maybe AllocationCallbacks ->  IO ()
destroySamplerYcbcrConversionKHR = destroySamplerYcbcrConversion

-- No documentation found for TopLevel "CHROMA_LOCATION_COSITED_EVEN_KHR"
pattern CHROMA_LOCATION_COSITED_EVEN_KHR :: VkChromaLocation
pattern CHROMA_LOCATION_COSITED_EVEN_KHR = CHROMA_LOCATION_COSITED_EVEN

-- No documentation found for TopLevel "CHROMA_LOCATION_MIDPOINT_KHR"
pattern CHROMA_LOCATION_MIDPOINT_KHR :: VkChromaLocation
pattern CHROMA_LOCATION_MIDPOINT_KHR = CHROMA_LOCATION_MIDPOINT

-- No documentation found for TopLevel "DEBUG_REPORT_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_KHR_EXT"
pattern DEBUG_REPORT_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_KHR_EXT :: VkDebugReportObjectTypeEXT
pattern DEBUG_REPORT_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_KHR_EXT = DEBUG_REPORT_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_EXT

-- No documentation found for TopLevel "FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16_KHR"
pattern FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16_KHR :: VkFormat
pattern FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16_KHR = FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16

-- No documentation found for TopLevel "FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16_KHR"
pattern FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16_KHR :: VkFormat
pattern FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16_KHR = FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16

-- No documentation found for TopLevel "FORMAT_B16G16R16G16_422_UNORM_KHR"
pattern FORMAT_B16G16R16G16_422_UNORM_KHR :: VkFormat
pattern FORMAT_B16G16R16G16_422_UNORM_KHR = FORMAT_B16G16R16G16_422_UNORM

-- No documentation found for TopLevel "FORMAT_B8G8R8G8_422_UNORM_KHR"
pattern FORMAT_B8G8R8G8_422_UNORM_KHR :: VkFormat
pattern FORMAT_B8G8R8G8_422_UNORM_KHR = FORMAT_B8G8R8G8_422_UNORM

-- No documentation found for TopLevel "FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT_KHR"
pattern FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT_KHR :: VkFormatFeatureFlagBits
pattern FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT_KHR = FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT

-- No documentation found for TopLevel "FORMAT_FEATURE_DISJOINT_BIT_KHR"
pattern FORMAT_FEATURE_DISJOINT_BIT_KHR :: VkFormatFeatureFlagBits
pattern FORMAT_FEATURE_DISJOINT_BIT_KHR = FORMAT_FEATURE_DISJOINT_BIT

-- No documentation found for TopLevel "FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT_KHR"
pattern FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT_KHR :: VkFormatFeatureFlagBits
pattern FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT_KHR = FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT

-- No documentation found for TopLevel "FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT_KHR"
pattern FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT_KHR :: VkFormatFeatureFlagBits
pattern FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT_KHR = FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT

-- No documentation found for TopLevel "FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT_KHR"
pattern FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT_KHR :: VkFormatFeatureFlagBits
pattern FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT_KHR = FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT

-- No documentation found for TopLevel "FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT_KHR"
pattern FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT_KHR :: VkFormatFeatureFlagBits
pattern FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT_KHR = FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT

-- No documentation found for TopLevel "FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT_KHR"
pattern FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT_KHR :: VkFormatFeatureFlagBits
pattern FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT_KHR = FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT

-- No documentation found for TopLevel "FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16_KHR"
pattern FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16_KHR :: VkFormat
pattern FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16_KHR = FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16

-- No documentation found for TopLevel "FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16_KHR"
pattern FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16_KHR :: VkFormat
pattern FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16_KHR = FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16

-- No documentation found for TopLevel "FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16_KHR"
pattern FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16_KHR :: VkFormat
pattern FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16_KHR = FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16

-- No documentation found for TopLevel "FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16_KHR"
pattern FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16_KHR :: VkFormat
pattern FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16_KHR = FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16

-- No documentation found for TopLevel "FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16_KHR"
pattern FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16_KHR :: VkFormat
pattern FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16_KHR = FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16

-- No documentation found for TopLevel "FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16_KHR"
pattern FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16_KHR :: VkFormat
pattern FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16_KHR = FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16

-- No documentation found for TopLevel "FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16_KHR"
pattern FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16_KHR :: VkFormat
pattern FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16_KHR = FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16

-- No documentation found for TopLevel "FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16_KHR"
pattern FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16_KHR :: VkFormat
pattern FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16_KHR = FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16

-- No documentation found for TopLevel "FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16_KHR"
pattern FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16_KHR :: VkFormat
pattern FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16_KHR = FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16

-- No documentation found for TopLevel "FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16_KHR"
pattern FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16_KHR :: VkFormat
pattern FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16_KHR = FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16

-- No documentation found for TopLevel "FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16_KHR"
pattern FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16_KHR :: VkFormat
pattern FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16_KHR = FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16

-- No documentation found for TopLevel "FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16_KHR"
pattern FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16_KHR :: VkFormat
pattern FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16_KHR = FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16

-- No documentation found for TopLevel "FORMAT_G16B16G16R16_422_UNORM_KHR"
pattern FORMAT_G16B16G16R16_422_UNORM_KHR :: VkFormat
pattern FORMAT_G16B16G16R16_422_UNORM_KHR = FORMAT_G16B16G16R16_422_UNORM

-- No documentation found for TopLevel "FORMAT_G16_B16R16_2PLANE_420_UNORM_KHR"
pattern FORMAT_G16_B16R16_2PLANE_420_UNORM_KHR :: VkFormat
pattern FORMAT_G16_B16R16_2PLANE_420_UNORM_KHR = FORMAT_G16_B16R16_2PLANE_420_UNORM

-- No documentation found for TopLevel "FORMAT_G16_B16R16_2PLANE_422_UNORM_KHR"
pattern FORMAT_G16_B16R16_2PLANE_422_UNORM_KHR :: VkFormat
pattern FORMAT_G16_B16R16_2PLANE_422_UNORM_KHR = FORMAT_G16_B16R16_2PLANE_422_UNORM

-- No documentation found for TopLevel "FORMAT_G16_B16_R16_3PLANE_420_UNORM_KHR"
pattern FORMAT_G16_B16_R16_3PLANE_420_UNORM_KHR :: VkFormat
pattern FORMAT_G16_B16_R16_3PLANE_420_UNORM_KHR = FORMAT_G16_B16_R16_3PLANE_420_UNORM

-- No documentation found for TopLevel "FORMAT_G16_B16_R16_3PLANE_422_UNORM_KHR"
pattern FORMAT_G16_B16_R16_3PLANE_422_UNORM_KHR :: VkFormat
pattern FORMAT_G16_B16_R16_3PLANE_422_UNORM_KHR = FORMAT_G16_B16_R16_3PLANE_422_UNORM

-- No documentation found for TopLevel "FORMAT_G16_B16_R16_3PLANE_444_UNORM_KHR"
pattern FORMAT_G16_B16_R16_3PLANE_444_UNORM_KHR :: VkFormat
pattern FORMAT_G16_B16_R16_3PLANE_444_UNORM_KHR = FORMAT_G16_B16_R16_3PLANE_444_UNORM

-- No documentation found for TopLevel "FORMAT_G8B8G8R8_422_UNORM_KHR"
pattern FORMAT_G8B8G8R8_422_UNORM_KHR :: VkFormat
pattern FORMAT_G8B8G8R8_422_UNORM_KHR = FORMAT_G8B8G8R8_422_UNORM

-- No documentation found for TopLevel "FORMAT_G8_B8R8_2PLANE_420_UNORM_KHR"
pattern FORMAT_G8_B8R8_2PLANE_420_UNORM_KHR :: VkFormat
pattern FORMAT_G8_B8R8_2PLANE_420_UNORM_KHR = FORMAT_G8_B8R8_2PLANE_420_UNORM

-- No documentation found for TopLevel "FORMAT_G8_B8R8_2PLANE_422_UNORM_KHR"
pattern FORMAT_G8_B8R8_2PLANE_422_UNORM_KHR :: VkFormat
pattern FORMAT_G8_B8R8_2PLANE_422_UNORM_KHR = FORMAT_G8_B8R8_2PLANE_422_UNORM

-- No documentation found for TopLevel "FORMAT_G8_B8_R8_3PLANE_420_UNORM_KHR"
pattern FORMAT_G8_B8_R8_3PLANE_420_UNORM_KHR :: VkFormat
pattern FORMAT_G8_B8_R8_3PLANE_420_UNORM_KHR = FORMAT_G8_B8_R8_3PLANE_420_UNORM

-- No documentation found for TopLevel "FORMAT_G8_B8_R8_3PLANE_422_UNORM_KHR"
pattern FORMAT_G8_B8_R8_3PLANE_422_UNORM_KHR :: VkFormat
pattern FORMAT_G8_B8_R8_3PLANE_422_UNORM_KHR = FORMAT_G8_B8_R8_3PLANE_422_UNORM

-- No documentation found for TopLevel "FORMAT_G8_B8_R8_3PLANE_444_UNORM_KHR"
pattern FORMAT_G8_B8_R8_3PLANE_444_UNORM_KHR :: VkFormat
pattern FORMAT_G8_B8_R8_3PLANE_444_UNORM_KHR = FORMAT_G8_B8_R8_3PLANE_444_UNORM

-- No documentation found for TopLevel "FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16_KHR"
pattern FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16_KHR :: VkFormat
pattern FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16_KHR = FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16

-- No documentation found for TopLevel "FORMAT_R10X6G10X6_UNORM_2PACK16_KHR"
pattern FORMAT_R10X6G10X6_UNORM_2PACK16_KHR :: VkFormat
pattern FORMAT_R10X6G10X6_UNORM_2PACK16_KHR = FORMAT_R10X6G10X6_UNORM_2PACK16

-- No documentation found for TopLevel "FORMAT_R10X6_UNORM_PACK16_KHR"
pattern FORMAT_R10X6_UNORM_PACK16_KHR :: VkFormat
pattern FORMAT_R10X6_UNORM_PACK16_KHR = FORMAT_R10X6_UNORM_PACK16

-- No documentation found for TopLevel "FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16_KHR"
pattern FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16_KHR :: VkFormat
pattern FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16_KHR = FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16

-- No documentation found for TopLevel "FORMAT_R12X4G12X4_UNORM_2PACK16_KHR"
pattern FORMAT_R12X4G12X4_UNORM_2PACK16_KHR :: VkFormat
pattern FORMAT_R12X4G12X4_UNORM_2PACK16_KHR = FORMAT_R12X4G12X4_UNORM_2PACK16

-- No documentation found for TopLevel "FORMAT_R12X4_UNORM_PACK16_KHR"
pattern FORMAT_R12X4_UNORM_PACK16_KHR :: VkFormat
pattern FORMAT_R12X4_UNORM_PACK16_KHR = FORMAT_R12X4_UNORM_PACK16

-- No documentation found for TopLevel "IMAGE_ASPECT_PLANE_0_BIT_KHR"
pattern IMAGE_ASPECT_PLANE_0_BIT_KHR :: VkImageAspectFlagBits
pattern IMAGE_ASPECT_PLANE_0_BIT_KHR = IMAGE_ASPECT_PLANE_0_BIT

-- No documentation found for TopLevel "IMAGE_ASPECT_PLANE_1_BIT_KHR"
pattern IMAGE_ASPECT_PLANE_1_BIT_KHR :: VkImageAspectFlagBits
pattern IMAGE_ASPECT_PLANE_1_BIT_KHR = IMAGE_ASPECT_PLANE_1_BIT

-- No documentation found for TopLevel "IMAGE_ASPECT_PLANE_2_BIT_KHR"
pattern IMAGE_ASPECT_PLANE_2_BIT_KHR :: VkImageAspectFlagBits
pattern IMAGE_ASPECT_PLANE_2_BIT_KHR = IMAGE_ASPECT_PLANE_2_BIT

-- No documentation found for TopLevel "IMAGE_CREATE_DISJOINT_BIT_KHR"
pattern IMAGE_CREATE_DISJOINT_BIT_KHR :: VkImageCreateFlagBits
pattern IMAGE_CREATE_DISJOINT_BIT_KHR = IMAGE_CREATE_DISJOINT_BIT

-- No documentation found for TopLevel "VK_KHR_SAMPLER_YCBCR_CONVERSION_EXTENSION_NAME"
pattern KHR_SAMPLER_YCBCR_CONVERSION_EXTENSION_NAME :: (Eq a, IsString a) => a
pattern KHR_SAMPLER_YCBCR_CONVERSION_EXTENSION_NAME = VK_KHR_SAMPLER_YCBCR_CONVERSION_EXTENSION_NAME

-- No documentation found for TopLevel "VK_KHR_SAMPLER_YCBCR_CONVERSION_SPEC_VERSION"
pattern KHR_SAMPLER_YCBCR_CONVERSION_SPEC_VERSION :: Integral a => a
pattern KHR_SAMPLER_YCBCR_CONVERSION_SPEC_VERSION = VK_KHR_SAMPLER_YCBCR_CONVERSION_SPEC_VERSION

-- No documentation found for TopLevel "OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_KHR"
pattern OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_KHR :: VkObjectType
pattern OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_KHR = OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION

-- No documentation found for TopLevel "SAMPLER_YCBCR_MODEL_CONVERSION_RGB_IDENTITY_KHR"
pattern SAMPLER_YCBCR_MODEL_CONVERSION_RGB_IDENTITY_KHR :: VkSamplerYcbcrModelConversion
pattern SAMPLER_YCBCR_MODEL_CONVERSION_RGB_IDENTITY_KHR = SAMPLER_YCBCR_MODEL_CONVERSION_RGB_IDENTITY

-- No documentation found for TopLevel "SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_2020_KHR"
pattern SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_2020_KHR :: VkSamplerYcbcrModelConversion
pattern SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_2020_KHR = SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_2020

-- No documentation found for TopLevel "SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_601_KHR"
pattern SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_601_KHR :: VkSamplerYcbcrModelConversion
pattern SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_601_KHR = SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_601

-- No documentation found for TopLevel "SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_709_KHR"
pattern SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_709_KHR :: VkSamplerYcbcrModelConversion
pattern SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_709_KHR = SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_709

-- No documentation found for TopLevel "SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_IDENTITY_KHR"
pattern SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_IDENTITY_KHR :: VkSamplerYcbcrModelConversion
pattern SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_IDENTITY_KHR = SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_IDENTITY

-- No documentation found for TopLevel "SAMPLER_YCBCR_RANGE_ITU_FULL_KHR"
pattern SAMPLER_YCBCR_RANGE_ITU_FULL_KHR :: VkSamplerYcbcrRange
pattern SAMPLER_YCBCR_RANGE_ITU_FULL_KHR = SAMPLER_YCBCR_RANGE_ITU_FULL

-- No documentation found for TopLevel "SAMPLER_YCBCR_RANGE_ITU_NARROW_KHR"
pattern SAMPLER_YCBCR_RANGE_ITU_NARROW_KHR :: VkSamplerYcbcrRange
pattern SAMPLER_YCBCR_RANGE_ITU_NARROW_KHR = SAMPLER_YCBCR_RANGE_ITU_NARROW

-- No documentation found for TopLevel "STRUCTURE_TYPE_BIND_IMAGE_PLANE_MEMORY_INFO_KHR"
pattern STRUCTURE_TYPE_BIND_IMAGE_PLANE_MEMORY_INFO_KHR :: VkStructureType
pattern STRUCTURE_TYPE_BIND_IMAGE_PLANE_MEMORY_INFO_KHR = STRUCTURE_TYPE_BIND_IMAGE_PLANE_MEMORY_INFO

-- No documentation found for TopLevel "STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO_KHR"
pattern STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO_KHR :: VkStructureType
pattern STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO_KHR = STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO

-- No documentation found for TopLevel "STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES_KHR"
pattern STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES_KHR :: VkStructureType
pattern STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES_KHR = STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES

-- No documentation found for TopLevel "STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO_KHR"
pattern STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO_KHR :: VkStructureType
pattern STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO_KHR = STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO

-- No documentation found for TopLevel "STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES_KHR"
pattern STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES_KHR :: VkStructureType
pattern STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES_KHR = STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES

-- No documentation found for TopLevel "STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_INFO_KHR"
pattern STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_INFO_KHR :: VkStructureType
pattern STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_INFO_KHR = STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_INFO
