{-# language CPP #-}
module Graphics.Vulkan.Extensions.VK_NV_dedicated_allocation_image_aliasing  (PhysicalDeviceDedicatedAllocationImageAliasingFeaturesNV) where

import Data.Kind (Type)
import Graphics.Vulkan.CStruct (FromCStruct)
import Graphics.Vulkan.CStruct (ToCStruct)
data PhysicalDeviceDedicatedAllocationImageAliasingFeaturesNV

instance ToCStruct PhysicalDeviceDedicatedAllocationImageAliasingFeaturesNV
instance Show PhysicalDeviceDedicatedAllocationImageAliasingFeaturesNV

instance FromCStruct PhysicalDeviceDedicatedAllocationImageAliasingFeaturesNV

