maintainer: generator.i.ardly.know.er@monoid.al
ghc-options:
- -Wall
- -fno-warn-unticked-promoted-constructors
- -fno-warn-name-shadowing
- -O2
- -flate-specialise
- -fspecialise-aggressively
default-extensions:
- BangPatterns
- BinaryLiterals
- BlockArguments
- ConstraintKinds
- DataKinds
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveGeneric
- DerivingVia
- DisambiguateRecordFields
- DuplicateRecordFields
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadComprehensions
- MultiParamTypeClasses
- MultiWayIf
- NoImplicitPrelude
- OverloadedStrings
- ParallelListComp
- PartialTypeSignatures
- PatternSynonyms
- PolyKinds
- RankNTypes
- RecordWildCards
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskellQuotes
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- ViewPatterns
name: generate-new
synopsis: A program to generate the vulkan package from the vulkan docs.
author: Ellie Hermaszewska
extra-source-files:
- readme.md
- package.yaml

library:
  source-dirs: src

internal-libraries:
  khronos-spec:
    source-dirs: khronos-spec
    dependencies:
    - generate-new

executables:
  vk:
    main: Main.hs
    source-dirs: vk
    dependencies:
    - generate-new
    - khronos-spec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  xr:
    main: Main.hs
    source-dirs: xr
    dependencies:
    - generate-new
    - khronos-spec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  vma:
    main: Main.hs
    source-dirs: vma
    dependencies:
    - generate-new
    - language-c
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

dependencies:
- algebraic-graphs
- ascii-progress
- async-pool
- attoparsec
- base
- bytestring
- casing
- containers
- data-default
- deepseq
- dependent-map >= 0.4
- dependent-sum >= 0.7.1
- directory
- extra
- filepath
- fourmolu
- inline-c
- interpolatedstring-perl6
- mtl
- pandoc
- parsec
- parsers
- polysemy >= 1.4 && < 1.7
- pretty-show
- prettyprinter
- regex-applicative
- relude
- replace-attoparsec >= 1.4.5
- safe
- say
- some
- tagsoup
- template-haskell
- text
- th-abstraction
- th-desugar >= 1.11
- th-orphans
- timeit
- transformers
- typed-process
- uniplate
- unordered-containers
- validation-selective
- vector
- vector-algorithms
- word-wrap
- xeno
